version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: container-example-server
    ports:
      - "80:80"
    

  mysql:
    image: mysql:latest
    restart: always
    container_name: container-example-db
    environment:
      MYSQL_ROOT_PASSWORD: Teste@123
      MYSQL_DATABASE: first_db
    ports:
      - "3306:3306"